[package]
name = "enclave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
edl = { path = "../edl", features = ["enclave"] }

[target.'cfg(not(target_vendor = "teaclave"))'.dependencies]
sgx_new_edl = { path = "../../../sgx_new_edl" }
sgx_types = { path = "../../../sgx_types" }
sgx_tstd = { path = "../../../sgx_tstd" }